toolkit: Always raise TemboardError
Fixes:

        Traceback (most recent call last):
          File "/home/bersace/src/dalibo/temboard/ui/temboardui/toolkit/app.py", line 312, in entrypoint
            retcode = self.main(argv, environ)
          File "/home/bersace/src/dalibo/temboard/ui/temboardui/cli/app.py", line 116, in main
            return command.main(args)
          File "/home/bersace/src/dalibo/temboard/ui/temboardui/cli/query_agent.py", line 70, in main
            response.raise_for_status()
          File "/home/bersace/src/dalibo/temboard/ui/temboardui/toolkit/http.py", line 155, in raise_for_status
            raise HTTPError(self.status, self.reason)
        TypeError: __init__() missing 3 required positional arguments: 'msg', 'hdrs', and 'fp'